---
name: Bug Report
description: Create a bug report.
labels:
  - type::bug
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Describe the buggy behavior in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Conda Info
      description: |
        Let's collect some basic information about your conda install.

        Please run the following command from your command line and paste the output below.

        ```bash
        conda info
        ```
      render: shell
  - type: textarea
    id: config
    attributes:
      label: Conda Config
      description: |
        Let's collect any customizations you may have for your conda install.

        Please run the following command from your command line and paste the output below.

        ```bash
        conda config --show-sources
        ```
      render: shell
  - type: textarea
    id: list
    attributes:
      label: Conda list
      description: |
        The packages installed into your environment can offer clues as to the problem you are facing.

        Please activate the environment within which you are encountering this bug, run the following command from your command line, and paste the output below.

        ```bash
        conda list --show-channel-urls
        ```
      render: shell
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Include any additional information (or screenshots) that you think would be valuable.
