---
name: Epic
description: A collection of related tickets.
labels:
  - epic
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: >-
        Define the high level objectives to be accomplished in this epic. Include the
        bigger picture of what is changing and/or the user story for why the
        changes are desired/necessary.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Linked Issues & PRs
      description: List all issues related to this epic.
      value: |
        - [ ] #
    validations:
      required: false
